# Automatically generated by configure - do not modify
TARGET_ABI_MIPSO32=y
TARGET_MIPS=y
TARGET_NAME=mips
TARGET_BASE_ARCH=mips
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
LDFLAGS+=
QEMU_CFLAGS+=
QEMU_CFLAGS+=-include mips.h
