# Automatically generated by configure - do not modify
TARGET_ARM=y
TARGET_NAME=armeb
TARGET_BASE_ARCH=arm
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
LDFLAGS+=
QEMU_CFLAGS+=
QEMU_CFLAGS+=-include armeb.h
