/* Automatically generated by create_config - do not modify */
#define HOST_X86_64 1
#define CONFIG_POSIX 1
#define CONFIG_LINUX 1
#define CONFIG_BYTESWAP_H 1
#define CONFIG_CPUID_H 1
#define CONFIG_INT128 1
