# Automatically generated by configure - do not modify
TARGET_ABI_MIPSN64=y
TARGET_MIPS64=y
TARGET_NAME=mips64el
TARGET_BASE_ARCH=mips
CONFIG_SOFTMMU=y
LDFLAGS+=
QEMU_CFLAGS+=
QEMU_CFLAGS+=-include mips64el.h
