# Automatically generated by configure - do not modify
TARGET_M68K=y
TARGET_NAME=m68k
TARGET_BASE_ARCH=m68k
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
LDFLAGS+=
QEMU_CFLAGS+=
QEMU_CFLAGS+=-include m68k.h
