# Automatically generated by configure - do not modify
TARGET_AARCH64=y
TARGET_NAME=aarch64eb
TARGET_BASE_ARCH=arm
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
LDFLAGS+=
QEMU_CFLAGS+=
QEMU_CFLAGS+=-include aarch64eb.h
