# Automatically generated by configure - do not modify
TARGET_SPARC=y
TARGET_NAME=sparc
TARGET_BASE_ARCH=sparc
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
LDFLAGS+=
QEMU_CFLAGS+=
QEMU_CFLAGS+=-include sparc.h
