# Automatically generated by configure - do not modify
TARGET_SPARC64=y
TARGET_NAME=sparc64
TARGET_BASE_ARCH=sparc
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
LDFLAGS+=
QEMU_CFLAGS+=
QEMU_CFLAGS+=-include sparc64.h
